# Generated by Django 4.1.3 on 2023-01-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_details', '0006_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
