# Generated by Django 4.1.3 on 2023-01-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_details', '0007_rename_companies_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
